PythonVersion="3.7.9"
virtualEnvName="antenv"
compressedVirtualEnvFile="antenv.tar.gz"
OperationId="|1RgFMNgR8hI=.498d9c83_"
SourceDirectoryInBuildContainer="/tmp/8d89213c4e161a5"
PlatformName="python"
